//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kullanici
    {
        public string ID { get; set; }
        public string sifre { get; set; }
        public Nullable<bool> IsValid { get; set; }
        public string eposta { get; set; }
    }
}
